name: Docker Image Pull and Tag

on:
 workflow_call:
    

jobs:
  docker-pull-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check current directory before checkout
        run: |
         pwd
         ls -la
         pwd
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          repository: viveky20/GHA-Calling-Repo
          ref: main
          #token: ${{ secrets.GHA_PAT }}
          path: './GHA-Calling-Repo'
      - name: Run check-git script
        run: |
          chmod +x GHA-Calling-Repo/scripts/checkgit-version.sh
          ./GHA-Calling-Repo/scripts/checkgit-version.sh
