name: Docker Image Pull and Tag

on:
 workflow_call:
    

jobs:
  docker-pull-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check current directory before checkout
        run: |
         pwd
         ls -la
         pwd
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          repository: viveky20/GHA-Calling-Repo
          ref: main
          #token: ${{ secrets.GHA_PAT }}
          path: './GHA-Calling-Repo'  
      - name: Check current directory
        run: |
         pwd
         ls -la
         pwd
      - name: Pull Docker Image
        run: |
          docker pull hello-world:latest
        env:
          image: ${{ github.event.inputs.image_name }}
      - name: Check current directory
        run: ./scripts/checkgit-version.sh
      - run: ./scripts/build.sh
      - name: Tag Docker Image
        run: |
          docker tag hello-world:latest  hello-world:${{ github.run_number }}
        env:
          image: ${{ github.event.inputs.image_name }}
